OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/Ta_small_angles_2;
SetBasePath;
SetPath;

CalibrateSource;
PowerUP;

RUN_TIME_1_spin 0; #hours
RUN_TIME_2_spin 15; #minutes
RUN_TIME_3_spin 0; #seconds
N_CAPTURES_spin 5000000; #events to capture
N_SEGMENTS_spin 100; #n. memory segments
CHANNEL_NAME_combo A; #input channel
CHANNEL_RANGE_combo 5V; #voltage range
RESOLUTION_combo 12bit; #ADC resolution
SAMPLESDIV_spin 500; #samples per div
SRMULTIPLIER_combo MS/s; #sample rate
SAMPLERATE_spin 200; #sample rate
TRIGGER_SOURCE_combo A; #trigger source
TRIGGER_text 500; #TRIGGER value mV
TRIGGER_DIRECTION_combo Falling; #trigger direction
PRETRIGGER_text 40; #pretrigger percent

STEP_ANGLE_text 0.9;
SetAngle;

CenterSource;
MOTOR_DIRECTION_Radio 0;
ChangeDIR;

FOR i,1,8,1:
RotateSource;
END_FOR;

MOTOR_DIRECTION_radio 1;
ChangeDIR;

RUN_TIME_1_spin 0; #hours
RUN_TIME_2_spin 20; #minutes
N_SEGMENTS_spin 100;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/Ta_small_angles_2/6_3;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/Ta_small_angles_2/5_4;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/Ta_small_angles_2/4_5;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/Ta_small_angles_2/3_6;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/Ta_small_angles_2/2_7;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/Ta_small_angles_2/1_8;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/Ta_small_angles_2/0_9;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/Ta_small_angles_2/0;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/Ta_small_angles_2/-0_9;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/Ta_small_angles_2/-1_8;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/Ta_small_angles_2/-2_7;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/Ta_small_angles_2/-3_6;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/Ta_small_angles_2/-4_5;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/Ta_small_angles_2/-5_4;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/Ta_small_angles_2/-6_3;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

FOR i,1,22,1:
RotateSource;
END_FOR;

RUN_TIME_1_spin 10; #hours
RUN_TIME_2_spin 0; #minutes
N_SEGMENTS_spin 1;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/Ta_small_angles_2/-25_2;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RUN_TIME_1_spin 30; #hours
RUN_TIME_2_spin 0; #minutes
N_SEGMENTS_spin 1;

FOR i,1,6,1:
RotateSource;
END_FOR;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/Ta_small_angles_2/-29_7;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

FOR i,1,6,1:
RotateSource;
END_FOR;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/Ta_small_angles_2/-34_2;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

FOR i,1,6,1:
RotateSource;
END_FOR;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/Ta_small_angles_2/-38_7;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

FOR i,1,6,1:
RotateSource;
END_FOR;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/Ta_small_angles_2/-43_2;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

FOR i,1,6,1:
RotateSource;
END_FOR;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/Ta_small_angles_2/-47_7;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

# Powering down the motor
PowerDOWN;
