OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/test_small_angles_new;
SetBasePath;
SetPath;

CalibrateSource;
PowerUP;

RUN_TIME_1_spin 0; #hours
RUN_TIME_2_spin 15; #minutes
RUN_TIME_3_spin 0; #seconds
N_CAPTURES_spin 5000000; #events to capture
N_SEGMENTS_spin 10; #n. memory segments
CHANNEL_NAME_combo A; #input channel
CHANNEL_RANGE_combo 5V; #voltage range
RESOLUTION_combo 12bit; #ADC resolution
SAMPLESDIV_spin 500; #samples per div
SRMULTIPLIER_combo MS/s; #sample rate
SAMPLERATE_spin 200; #sample rate
TRIGGER_SOURCE_combo A; #trigger source
TRIGGER_text 500; #TRIGGER value mV
TRIGGER_DIRECTION_combo Falling; #trigger direction
PRETRIGGER_text 40; #pretrigger percent

STEP_ANGLE_text 0.9;
SetAngle;

CenterSource;
MOTOR_DIRECTION_radio 0;
ChangeDIR;

FOR i,1,18,1:
RotateSource;
END_FOR;

MOTOR_DIRECTION_radio 1;
ChangeDIR;


RUN_TIME_2_spin 45;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/test_small_angles_new/15_3;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/test_small_angles_new/14_4;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/test_small_angles_new/13_5;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/test_small_angles_new/12_6;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/test_small_angles_new/11_7;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/test_small_angles_new/10_8;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/test_small_angles_new/9_9;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

RUN_TIME_1_spin 0;
RUN_TIME_2_spin 10;
N_SEGMENTS_spin 100;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/test_small_angles_new/9_0;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/test_small_angles_new/8_1;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/test_small_angles_new/7_2;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/test_small_angles_new/6_3;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/test_small_angles_new/5_4;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/test_small_angles_new/4_5;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/test_small_angles_new/3_6;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/test_small_angles_new/2_7;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/test_small_angles_new/1_8;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/test_small_angles_new/0_9;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/test_small_angles_new/0;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/test_small_angles_new/-0_9;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/test_small_angles_new/-1_8;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/test_small_angles_new/-2_7;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/test_small_angles_new/-3_6;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/test_small_angles_new/-4_5;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/test_small_angles_new/-5_4;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/test_small_angles_new/-6_3;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/test_small_angles_new/-7_2;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/test_small_angles_new/-8_1;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/test_small_angles_new/-9_0;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

RUN_TIME_2_spin 45;
N_SEGMENTS_spin 10;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/test_small_angles_new/-9_9;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/test_small_angles_new/-10_8;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/test_small_angles_new/-11_7;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/test_small_angles_new/-12_6;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/test_small_angles_new/-13_5;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/test_small_angles_new/-14_4;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/test_small_angles_new/-15_3;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

# Powering down the motor
PowerDOWN;
