OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/X_small_angles;
SetBasePath;
SetPath;

CalibrateSource;
PowerUP;

RUN_TIME_1_spin 0; #hours
RUN_TIME_2_spin 15; #minutes
RUN_TIME_3_spin 0; #seconds
N_CAPTURES_spin 5000000; #events to capture
N_SEGMENTS_spin 1; #n. memory segments
CHANNEL_NAME_combo A; #input channel
CHANNEL_RANGE_combo 5V; #voltage range
RESOLUTION_combo 12bit; #ADC resolution
SAMPLESDIV_spin 500; #samples per div
SRMULTIPLIER_combo MS/s; #sample rate
SAMPLERATE_spin 200; #sample rate
TRIGGER_SOURCE_combo A; #trigger source
TRIGGER_text 200; #TRIGGER value mV
TRIGGER_DIRECTION_combo Falling; #trigger direction
PRETRIGGER_text 40; #pretrigger percent

STEP_ANGLE_text 0.9;
SetAngle;

CenterSource;
MOTOR_DIRECTION_radio 0;
ChangeDIR;

FOR i,1,18,1:
RotateSource;
END_FOR;

MOTOR_DIRECTION_radio 1;
ChangeDIR;


RUN_TIME_1_spin 3; #hours
RUN_TIME_2_spin 0; #minutes
N_SEGMENTS_spin 10; #n. memory segments

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/X_small_angles/15_3;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/X_small_angles/14_4;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/X_small_angles/13_5;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/X_small_angles/12_6;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/X_small_angles/11_7;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/X_small_angles/10_8;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/X_small_angles/9_9;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

RUN_TIME_1_spin 2;
RUN_TIME_2_spin 0;
N_SEGMENTS_spin 10;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/X_small_angles/9_0;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/X_small_angles/8_1;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/X_small_angles/7_2;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/X_small_angles/6_3;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/X_small_angles/5_4;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/X_small_angles/4_5;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/X_small_angles/3_6;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/X_small_angles/2_7;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/X_small_angles/1_8;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/X_small_angles/0_9;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/X_small_angles/0;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/X_small_angles/-0_9;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/X_small_angles/-1_8;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/X_small_angles/-2_7;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/X_small_angles/-3_6;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/X_small_angles/-4_5;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/X_small_angles/-5_4;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/X_small_angles/-6_3;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/X_small_angles/-7_2;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/X_small_angles/-8_1;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/X_small_angles/-9_0;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

RUN_TIME_1_spin 3; #hours
RUN_TIME_2_spin 0; #minutes
N_SEGMENTS_spin 10;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/X_small_angles/-9_9;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/X_small_angles/-10_8;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/X_small_angles/-11_7;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/X_small_angles/-12_6;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/X_small_angles/-13_5;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/X_small_angles/-14_4;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

RotateSource;

OUTPUT_PATH_text /home/collazuo/Scrivania/Rutherford_2024/X_small_angles/-15_3;
SetPath;
DataCollection;
PicoScopeStart;
DataCollection;

# Powering down the motor
PowerDOWN;
