//non pointlike source, no iterations, 1 collimator, E_loss, scattering in the target with steps, 
//correct angle distribution and with the correct probability, correct geometric description
#include<iostream>
#include<random>
#include<cmath>
#include<fstream>
#include <TROOT.h>
#include <TH1D.h>
#include <TH2D.h>
#include <TH3D.h>
#include <TVector3.h>
using namespace std;

struct particle {
	float position[3]; //x,y,z
	float energy;
};
TVector3 direction; //dy, dx, dz ! dx and dy are swapped!
const float  pi=3.141592653589793;
float activity=364430.;  

void Scattering(int s)
{
	int Npart=1E+07, Ndetect=0, Nlost_before_coll=0, Nlost_after_scatt=0; //number of particle to simulate, number of detected particle (per second)
	float x_coll=2.115, y_coll=0.1925, z_coll=0.3425; //collimator1 position (x_coll) and dimentions (-y_coll;y_coll) and (-z_coll;z_coll) (in cm)
	
	float teta_det=(s*0.9*pi/180.), y_det=0.17, z_det=0.175; //angle and dimentions of the detector, from (-y_det;y_det) and (-z_det;z_det) (in cm)
	float r_det=7.81; //distance from target to detector, in cm
	float r_source=0.275;
	float teta_p;
	
	float path1=sqrt(pow(x_coll, 2)+pow(y_coll+r_source, 2)+pow(z_coll+r_source, 2));	//after that all particle emitted with proper angle should have reached x_coll, (order 0.06 cm)
	float stepAu=0.00000102; //given the mean free path lambda=0.1 um, stepAu=lambda/10=1*E-06 cm, target thickness is d=0.17 um=1.7 E-05 cm
	float eloss, ang_stragg;
	float x_target=0.000016; //target width
	
	float eloss_air=0.001, eloss_au=0.0044; //different values for e_loss (in MeV)
	float t=(4./197.); //mass ratio
	
	
	TH1D *teta_hist = new TH1D("teta_hist","Teta angle distribution of beam profile (in deg)",99,-44.55,44.55); //for beam profile, 99 bins
	//TH1D *teta_hist = new TH1D("teta_hist","Teta distribution after scattering (in deg)", 199,-89.55,89.55); //for scattering profile, 199 bins
	TH1D *phi_hist = new TH1D("phi_hist","Phi angle distribution after scattering (in deg)",72,-180.0,180.0);
	TH2D *XYplane = new TH2D("XYplane","Y,X position after scattering",100,-10,10,100,-0.1,10);
	TH3D *plot = new TH3D("plot","X,Y,Z position after scattering",100,-0.1,10,100,-10,10,100,-10,10);
	
	TH3D *pos = new TH3D("pos","X,Y,Z position check",100,-0.1,10,100,-10,10,100,-10,10);
	TH1D *teta_b = new TH1D("teta_b","Teta angle distribution generated by b (in deg)",360,-180.0,180.0);
	TH1D *teta_before = new TH1D("teta_before","Teta angle distribution before scattering (in deg)",60,-3.0,3.0);
	TH1D *Eloss = new TH1D("Eloss","Energy lost in the target",500, 0., 6.);
	TH1D *teta_stragg = new TH1D("teta_stragg","Angular straggling in the target",100, -10., 10.);
	
	ofstream write("ParticleRate.txt");
	
	particle part;
	random_device rd;	//oggetto rd
	uniform_real_distribution<float> random(0, 1);
	uniform_real_distribution<float> direct(-1.,1.);
	normal_distribution <float> energy(4.7, 0.1);

	uniform_real_distribution<float> PHI(0.,2*pi); 
	uniform_real_distribution<float> b_impact(0., 0.15); //expressed in nm, bmax=1.3nm but too many at small angles..., 0.015 can be good
	
	uniform_int_distribution<int> even(1.0, 100.0);
	uniform_int_distribution<int> event(1, 1000);
	
	
	cout<<"\nDetector placed at "<<teta_det*(180/pi)<<" deg";
	cout<<"\nNumber of particles generated: "<<Npart<<"\n\n";
													
	for (int i=0; i<Npart; i++) 		//loop on all particles
	{
		if (i%(Npart/10)==0) cout<<"particle "<<i<<endl;
		
		for (int i=0; i<3; i++) {direction(i)=0;}
		bool pass=false, detect=false;
		float norm2=0;
		
		float rand=random(rd);
		float rand2=random(rd);
		float rad=r_source*sqrt(rand);
		float t=rand2*2*pi;
		
		part.position[0]=0.;
		part.position[1]=rad*cos(t);
		part.position[2]=rad*sin(t);
		
		for (int j=0; j<3; j++) {direction(j)=direct(rd);	}
		for (int j=0; j<3; j++) {direction(j)/=direction.Mag(); }
		part.energy=energy(rd);			
		
		if (direction(1)<=0) { 	//if dx<0 particle is lost
			Nlost_before_coll++;
			continue;					
		} 
		
			
		////////////////////////////////////////////////// untill the particle reaches the target
		
		float x1, y1, z1;
		x1=part.position[0]+direction(1)*path1;		//predict position after collimator
		y1=part.position[1]+direction(0)*path1;
		z1=part.position[2]+direction(2)*path1;				
		//part.energy-=eloss_air;
			
		if (abs(y1/x1)<(y_coll/x_coll) && abs(z1/x1)<(z_coll/x_coll)) pass=true;
		
			
		if (!pass) {
			Nlost_before_coll++;
			continue;	}
		
		part.position[0]=0.; //update positions, new x position refeared to target
		if (direction(1)!=0) {
			part.position[1]+=(direction(0)/direction(1))*x_coll;
			part.position[2]+=(direction(2)/direction(1))*x_coll;
		}
		else continue;
		
		pos->Fill(part.position[0], part.position[1], part.position[2]);
		teta_before->Fill(direction.Phi()); //what we call teta
		
			/////////////////////////////////////////////////////////// target interaction
			eloss=0;
			ang_stragg=direction.Phi()*180/pi;
			while ((part.position[0]<x_target) && abs(part.position[1])<0.2 && abs(part.position[2])<0.35 && part.energy>0) { ///////while the particle is in the target
				
				int ev= event(rd);
				if (ev<=36) {	//the particle is scattered
					
				float phi= PHI(rd);
				float b= b_impact(rd);
				int e= even(rd);
				if (e%2==0) b=-b; //generating also negative b
				float energyCM=part.energy*79./(79.+4.)	;
				float teta=2*atan(0.000113757/(energyCM*b)); //in rad
				teta_b->Fill(teta*180/pi);
					
				//update directions 
				direction.SetPhi(direction.Phi()+teta); //what we call teta, for root is Phi
				direction.SetTheta(direction.Theta()+phi); ////what we call phi, for root is Theta
				}
				
				for (int k=0; k<3; k++) { direction(k)/=direction.Mag(); } //renormalize directions dy,dx,dz
				
				part.position[0]+=direction(1)*stepAu;		//predict position after collimator
				part.position[1]+=direction(0)*stepAu;
				part.position[2]+=direction(2)*stepAu;
				part.energy-=eloss_au; //0.0044 MeV lost after a step of 10E-02 um, from LISE++
				eloss+=eloss_au;
			}	
		if (part.energy<=0) continue;
		Eloss->Fill(eloss);
		ang_stragg-=direction.Phi()*180/pi;
		teta_stragg->Fill(ang_stragg);	
		/////////////////////////////////////////////////////////// from target to detector
		
		//update position, trivial path if doesn't reach the detector
			part.position[0]+=direction(1)*r_det;		//predict position after collimator
			part.position[1]+=direction(0)*r_det;
			part.position[2]+=direction(2)*r_det;
			//part.energy-=eloss_air;
			
			teta_p=atan(part.position[1]/part.position[0]);
			
			//chech if the particle ends in the detector
			if ( teta_p < (teta_det + atan(y_det/r_det) ) && teta_p > (teta_det - atan(y_det/r_det) ) ) { //teta condition
				
					if (part.position[2]>-z_det && part.position[2]<z_det) {//Ndetect++;	
					detect=true;} //z condition
			}
			

		///////////////// Fill histograms and compute number of scattered, detected...
		
		float part_angle=atan(part.position[2]/(sqrt(part.position[0]*part.position[0]+part.position[1]*part.position[1]))); //angle respect to detector plane
		if ((part_angle>atan(-z_det/r_det))&&(part_angle<atan(z_det/r_det))) {
			
			XYplane->Fill(part.position[1], part.position[0]);
			teta_hist->Fill(teta_p*180/pi);
		}
		 
		plot->Fill(part.position[0], part.position[1], part.position[2]);
		phi_hist->Fill(part_angle*180/pi);
		
		if (!detect) Nlost_after_scatt++;
		
		if ((pass) && (detect) && (part.energy>=0)) Ndetect++;
		
	}				
	
	cout<<"\nN detected: "<<Ndetect<<endl;
	cout<<"Acquisition time: "<<(Npart/activity)<<endl;
	cout<<"Rate: "<<Ndetect/(Npart/activity)<<endl;
	cout<<"N lost before the collimator: "<<Nlost_before_coll<<endl;
	cout<<"N lost after the collimator: "<<Nlost_after_scatt<<endl;
	
	//TCanvas *c1 = new TCanvas("c1");
    //c1->SetLogy();
    Double_t scale = (activity/Npart);
    teta_hist->Scale(scale);
    
    /*for (int k=0; k<99; k++) { //change number of bins depending on beam profile (99) or scattering profile (199)
    	write << teta_hist->GetBinCenter(k) << "\t" << teta_hist->GetBinContent(k) << endl;
	}*/
    
	//teta_hist->Draw("HIST");
	
}
